apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-endpoint
  namespace: retry-test-project
spec:
  hosts:
    - retry-endpoint
  http:
    - match:
        - uri:
            prefix: /abc
      name: test1
      retries:
        attempts: 1
        perTryTimeout: 1s
        retryOn: 'retriable-4xx'
      route:
        - destination:
            host: retry-endpoint
    - name: test2
      retries:
        attempts: 2
        perTryTimeout: 2s
        retryOn: '5xx,reset'
      route:
        - destination:
            host: retry-endpoint